### ISSUE TITLE
Support tcx files

### ISSUE THREAD

**Issue by supermiwil** [imker25/gpsa#24]
Maybe it is possible to add a .tcx support to this tool as it currently only supports .gpx files.
I am a "Endomondo" user and those guys only provide a full dump of personal workouts in a tcx format :(

Please find attached some test data to compare "endomondo tcx & gpx" 
[testDataMiwil.zip](https://github.com/imker25/gpsa/files/4583652/testDataMiwil.zip)

**Comment by imker25** [comment]
Thanks for the test data. I will implement the *.tcx support soon

**Comment by imker25** [comment]
I work on this feature on branch feature/TcxSupport

**Comment by imker25** [comment]
Implementation merged to master with 2796cc873edd62cbd9c6ff993f664bf20e64b904
